export enum UserRole {
  CONSUMER = 'CONSUMER',
  STORE_OWNER = 'STORE_OWNER',
  COURIER = 'COURIER',
  ADMIN = 'ADMIN',
}

export enum StoreStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PREPARING = 'PREPARING',
  READY = 'READY',
  PICKED_UP = 'PICKED_UP',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  PIX = 'PIX',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  WALLET = 'WALLET',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum DeliveryStatus {
  SEARCHING_COURIER = 'SEARCHING_COURIER',
  COURIER_ASSIGNED = 'COURIER_ASSIGNED',
  COURIER_HEADING_TO_STORE = 'COURIER_HEADING_TO_STORE',
  COURIER_AT_STORE = 'COURIER_AT_STORE',
  PICKED_UP = 'PICKED_UP',
  HEADING_TO_CLIENT = 'HEADING_TO_CLIENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
}

export enum CourierStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum TransactionType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}

export enum NotificationType {
  ORDER_UPDATE = 'ORDER_UPDATE',
  DELIVERY_UPDATE = 'DELIVERY_UPDATE',
  PAYMENT = 'PAYMENT',
  PROMOTION = 'PROMOTION',
  SYSTEM = 'SYSTEM',
}
